package org.example;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import javax.swing.*;
import java.awt.*;

public class SaveStudentIHM extends JPanel {
    private JButton jbSave;
    private JButton jbLoad;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JTextField jtfNote;
    private JTextField jtfName;
    private JLabel jcomp7;

    public SaveStudentIHM() {
        //construct components
        jbSave = new JButton("Save");
        jbLoad = new JButton("Load");
        jcomp3 = new JLabel("Nom : ");
        jcomp4 = new JLabel("Note : ");
        jtfNote = new JTextField(5);
        jtfName = new JTextField(5);
        jcomp7 = new JLabel("Charger / Sauvegarder un étudiant");

        //adjust size and set layout
        setPreferredSize(new Dimension(249, 146));
        setLayout(null);

        //add components
        add(jbSave);
        add(jbLoad);
        add(jcomp3);
        add(jcomp4);
        add(jtfNote);
        add(jtfName);
        add(jcomp7);

        //set component bounds (only needed by Absolute Positioning)
        jbSave.setBounds(10, 105, 100, 20);
        jbLoad.setBounds(125, 105, 100, 20);
        jcomp3.setBounds(20, 35, 100, 25);
        jcomp4.setBounds(20, 65, 100, 25);
        jtfNote.setBounds(80, 65, 100, 25);
        jtfName.setBounds(80, 35, 100, 25);
        jcomp7.setBounds(20, 5, 205, 25);
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("MyPanel");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new SaveStudentIHM());
        frame.pack();
        frame.setVisible(true);
    }
}

